### ISSUE TITLE
Failed to load entry from component (IE)

### ISSUE THREAD

**Issue by robiharid** [SharePoint/sp-dev-fx-webparts#1084]
I get this error running on IE, works fine on Chrome et al.

```
[SPLoaderError.loadComponentError]:
***Failed to load component "3aac0bde-0ef1-46a1-a7f4-216112d395d5" (CompactCustomListWebPart). Original error: ***Failed to load entry point from component "3aac0bde-0ef1-46a1-a7f4-216112d395d5" (CompactCustomListWebPart). Original error: Error loading https://component-id.invalid/3aac0bde-0ef1-46a1-a7f4-216112d395d5_0.0.1
 https://component-id.invalid/3aac0bde-0ef1-46a1-a7f4-216112d395d5_0.0.1 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.

***INNERERROR:
***Failed to load entry point from component "3aac0bde-0ef1-46a1-a7f4-216112d395d5" (CompactCustomListWebPart). Original error: Error loading https://component-id.invalid/3aac0bde-0ef1-46a1-a7f4-216112d395d5_0.0.1
 https://component-id.invalid/3aac0bde-0ef1-46a1-a7f4-216112d395d5_0.0.1 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.
***CALLSTACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:4:53963)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:4:53499)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:20:118832)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:20:128525)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:20:124550)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:20:115044)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:1:16156)
   at F (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:1:16132)
   at C (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:1:15977)
   at B (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js:1:15565)
```

I have incorporated gulp clean into the build script so it always cleans before builds. 

Someone suggested that the external CDN reference to Fabric was causing this issue? How would I bundle it myself?

Perhaps it is the sp web pnp js import that uses newer stuff - do I need to add poly fill to every tsx file that uses sp, or only the mainwebpart.ts? `
import '@pnp/polyfill-ie11';`
(https://pnp.github.io/pnpjs/documentation/polyfill/)

**Comment by jpalo** [comment]
Go to IE11 console, you should find correct error message there. Mine was caused by using RegExp syntax not supported by IE11 and interestingly the topmost error sawn by the users was that confusing HTTPS error.

**Comment by hugoabernier** [comment]
@robiharid did @jpalo 's answer help you with your issues?

I'll mark this as closed, but feel free to re-open it if you need more help.

Thanks @jpalo  for your help with this.
