### ISSUE TITLE
Gulp tasks fail: Cannot find module "microsoft/sp-build-web"

### ISSUE THREAD

**Issue by sganta** [SharePoint/sp-dev-fx-webparts#1146]
## Category

- [ ] Question
- [x] Bug
- [] Enhancement

## Expected or Desired Behavior

I have node version 10.19.0. I have gulp version 3.9.1. I have npm version 6.13.7

I am able to build and debug a new hello world webpart solution. I wanted to try js-display-list webpart. I ran the following commands:

npm install 
gulp serve

I was expecting to try the js-display-list sample webpart on my hosted workbench. 

## Observed Behavior

I get the following error at the end of "gulp serve".

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\Sharepoint Projects\sp-dev-fx-webparts\samples\js-employee-spotlight\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by sganta** [comment]
I have tried 

 npm install --save-dev @micrsoft/sp-build-web

 Following is what I got

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@micrsoft%2fsp-build-web - Not found
npm ERR! 404
npm ERR! 404  '@micrsoft/sp-build-web@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!    ...\AppData\Roaming\npm-cache\_logs\2020-02-22T17_37_24_309Z-debug.log
