### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by tejasthite** [SharePoint/sp-dev-fx-webparts#1198]
Dear All, I keep getting this when executing Gulp Serve any help will be appreciated

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\tejast\Documents\GitHub\code\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\tejast\Documents\GitHub\code\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\tejast\Documents\GitHub\code\node_modules\gulp\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\tejast\Documents\GitHub\code\node_modules\gulp\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)

**Comment by sudharsank** [comment]
Hi, Can you please let us know the following details
1. Node Version
2. Gulp Version
3. SharePoint generator version

Make sure you use the correct version of the above mentioned in the below URL.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

If all the versions are correctly used then try the below
https://timonweb.com/posts/how-to-fix-referenceerror-primordials-is-not-defined-error/

**Comment by tejasthite** [comment]
@hugoabernier - Thank you very much for the help and tagging this.
@sudharsank  - Much appreciate your help!

**Comment by bgourav55** [comment]
I am facing the same issue where it said "ReferenceError: primordials is not defined".

Node version: v12.18.4
Gulp Version: CLI version: 2.3.0 & Local version: 3.9.1  
Sharepoint Generator Version: 1.11.0

I also followed the steps mentioned in the second URL mentioned by @sudharsank 

Now I am getting the following error while running gulp : 

Error: Your dev environment is running NodeJS version v12.18.4 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0 || >=10.13.0 <11.0.0
    at SPWebBuildRig.initialize (E:\Code\SPFx\FirstWebPart\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:26:19)
    at Object.exports.initialize (E:\Code\SPFx\FirstWebPart\node_modules\@microsoft\sp-build-web\lib\index.js:22:17)
    at Object.<anonymous> (E:\Code\SPFx\FirstWebPart\gulpfile.js:7:7)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireOrImport (C:\Users\grvbo\AppData\Roaming\npm\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)
    at execute (C:\Users\grvbo\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:30:3)
    at Liftoff.handleArguments (C:\Users\grvbo\AppData\Roaming\npm\node_modules\gulp-cli\index.js:211:24)
    at Liftoff.execute (C:\Users\grvbo\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:201:12)
    at module.exports (C:\Users\grvbo\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (C:\Users\grvbo\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:191:5)
    at C:\Users\grvbo\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:149:9

Kindly suggest how to resolve the issue

**Comment by sudharsank** [comment]
@bgourav55 your node version is 12 which is still not supported by spfx. Use nvm to install node version 10 and use the version 10.

Happy coding...

**Comment by bgourav55** [comment]
Downgrading to node version 10.22.0 fixed the issue...  
Thanks a lot

**Comment by Aymkdn** [comment]
It appears we need spfx v1.12.1 to have compatibility with Node 12.
