### ISSUE TITLE
react-content-query-webpart gulp serve error

### ISSUE THREAD

**Issue by inehme** [SharePoint/sp-dev-fx-webparts#1237]
I have clone the repo, then did an npm install and installed all packages. When I did a gulp serve I got the error below. Any help is greatly appreciated.

Build target: DEBUG
C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178
            throw new Error(prefix + os.EOL +
            ^

Error: JSON validation failed:
C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\config\tslint.json
Error: #/ (Defines configuration options for the...)
       Additional properties not allowed: lintConfig,useDefaultConfigAsBase,removeExistingRules,displayAsWarning
    at validateObjectWithCallback (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)        
    at JsonSchema.validateObject (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
    at TslintCmdTask._readConfigFile (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:311:28)
    at TslintCmdTask.onRegister (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
    at Object.initialize (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\gulp-core-build\lib\index.js:300:24)
    at SPWebBuildRig.initialize (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
    at SPWebBuildRig.initialize (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:30:15)
    at Object.exports.initialize (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\node_modules\@microsoft\sp-build-web\lib\index.js:22:17)
    at Object.<anonymous> (C:\Users\ibrahim.nehme\source\sp-dev-fx-webparts\samples\react-content-query-webpart\gulpfile.js:29:7)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

**Comment by inehme** [comment]
fixed the issue
