### ISSUE TITLE
Error ceating a simple WebPart (HelloWorld)

### ISSUE THREAD

**Issue by jtlivio** [SharePoint/sp-dev-fx-webparts#55]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Hi, after follow all procedures in a Linux Environment (Debian 8), i can not build anymore any WebPart. I tried also another installation from scratch in another machine.

Any clue on this behavior?
Thanks

**DROP 5**

**Generic Error**

```
Error - 'tslint' sub task errored after 871 ms 
 Error in plugin 'gulp-cache'
Message:
    Cannot find module './h6'
Details:
    code: MODULE_NOT_FOUND
```  

**Detailed Error**

```
Details:
    code: MODULE_NOT_FOUND
Error: Cannot find module './h6'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jlivio/spfx/helloworld-webpart/node_modules/@microsoft/sp-tslint-rules/lib/utils/implicitRoles/index.js:34:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jlivio/spfx/helloworld-webpart/node_modules/@microsoft/sp-tslint-rules/lib/utils/getImplicitRole.js:2:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jlivio/spfx/helloworld-webpart/node_modules/@microsoft/sp-tslint-rules/lib/rules/a11yRoleHasRequiredAriaPropsRule.js:14:25)
    at Module._compile (module.js:570:32)
```

**Comment by waldekmastykarz** [comment]
This is a known bug caused by the fact that linux is case-sensitive and ./h6 is in fact ./H6. Check out https://github.com/SharePoint/sp-dev-docs/issues/246#issuecomment-255311473 for more info.

**Comment by jtlivio** [comment]
Thanks @waldekmastykarz :)

**Comment by VesaJuvonen** [comment]
Closing as seems to be answered and no recent activity.
