### ISSUE TITLE
Can't scaffold new projects

### ISSUE THREAD

**Issue by aaronhawryluk** [SharePoint/sp-dev-fx-webparts#600]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior
With node 10.9.0:
yodoctor shows no errors
yo scaffolds project

## Observed Behavior
With node 10.9.0:
yodoctor shows:

> yodoctor

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version
√ NODE_PATH matches the npm root
× yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

Found potential issues on your machine :(
+ yo@2.0.5
updated 1 package in 7.506s

yo scaffolding fails with:
λ yo @microsoft/sharepoint
C:\Users\XXXXX\AppData\Roaming\npm\node_modules\yo\node_modules\global-tunnel-ng\index.js:226
    throw e;
    ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Url.parse (url.js:334:19)
    at urlParse (url.js:144:13)
    at tryParse (C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\yo\node_modules\global-tunnel-ng\index.js:75:16)
    at Object.globalTunnel.initialize (C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\yo\node_modules\global-tunnel-ng\index.js:176:14)
    at Object.<anonymous> (C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\yo\lib\cli.js:20:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

## Steps to Reproduce

(Install node 10.9.0 64-bit)
npm install npm -g (to update)
npm install -g yo gulp
yo @microsoft/sharepoint

**Comment by VesaJuvonen** [comment]
As this is a generic question and not related to the samples in this repository, it should be asked in sp-dev-docs repository, as we have multiple engineers and support people helping there. In short - nodeJs v10.9 is not currently supported by SPFx - we only support SLT version which currently is 8.11.4.

**Comment by aaronhawryluk** [comment]
Thanks @VesaJuvonen, that helps a lot.
