### ISSUE TITLE
Cannot find module 'webpack-bundle-analyzer'

### ISSUE THREAD

**Issue by Azhakeswari** [SharePoint/sp-dev-fx-webparts#608]
Error: Cannot find module 'webpack-bundle-analyzer'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (scriptdemo\gulpfile.js:6:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (AppData\Roaming\npm\node_mo
dules\gulp\bin\gulp.js:116:3)
    at Liftoff.execute (AppData\Roaming\npm\node_modules\gu
lp\node_modules\liftoff\index.js:203:12)
    at module.exports (AppData\Roaming\npm\node_modules\gul
p\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (ppData\Roaming\npm\node_module
s\gulp\node_modules\liftoff\index.js:195:5)

kindly help me to solve this issue.

**Comment by VelinGeorgiev** [comment]
Add the 'webpack-bundle-analyzer' package to your solution:
```npm install webpack-bundle-analyzer --save-dev```

More info: [https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/optimize-builds-for-production.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/optimize-builds-for-production.md)

**Comment by VelinGeorgiev** [comment]
@Azhakeswari where you able to follow the url I have sent you? Do you still have issues?

**Comment by Azhakeswari** [comment]
Thanks @VelinGeorgiev .Issue is resolved.

**Comment by yxiuzhu** [comment]
THX
