### ISSUE TITLE
Web part is not showing up in sharepoint site

### ISSUE THREAD

**Issue by Azhakeswari** [SharePoint/sp-dev-fx-webparts#612]
## Category
- [ ] Question
- [x] Bug
- [x] Enhancement

## Authors
@wobba 
https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/react-script-editor
## Expected or Desired Behavior

I am trying to test the sample with your code
https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/react-script-editor
it is working fine in local host but not showing up in web part share point site

## Steps to Reproduce
I have follwed the steps given in the link (https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/react-script-editor)

It might throw different error and warnings.

Let me know the dependencies. 

kindly help me resolve this issue.

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
Is it a modern site? If so you must either enable it to allow custom scripting, or build the part to work on all sites by changing the manifest.

**Comment by itsknob** [comment]
To add to @wobba's point, [you can find the documentation on that here.](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script)

**Comment by Azhakeswari** [comment]
@wobba ,Yes it is a Modern site.
**build the part to work on all sites by changing the manifest.**:what changes should i do for it in manifest?.
Kindly explain in detail.

@itsknob ,thanks for the documentation.

**Comment by Azhakeswari** [comment]
@wobba and @itsknob custom script option is enabled.

Kindly help me solve this issue.

Thanks.

**Comment by wobba** [comment]
@Azhakeswari as long as you know what you are doing, and implications of allowing this web part all over, do the following.

Edit `ScriptEditorWebPart.manifest.json` and change `requiresCustomScript` to false. Then rebuild. This allows you to install the part on any site, regardless of the allowing custom script or not - even though the web part clearly allows custom script. It's a reason why the default parameters are set this way :)

**Comment by Azhakeswari** [comment]
Hi,
Hello world web part is working fine in Modern Team site,Communication site as well as in classic team site.
But the script which i tested from this link(https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor) is not showing up in Modern Teamsite and CommunicationSite.

@wobba Kindly help me solve this issue.

Thanks.

**Comment by Azhakeswari** [comment]
Thanks @wobba it is working fine...:)

**Comment by wobba** [comment]
And for anyone reading this thread. You should really think things thru before going this route. If it's custom functionality you might be better off creating a custom SPFx part with that logic instead of using this poor-mans migration route.

**Comment by Azhakeswari** [comment]
Hi,

It worked fine previously.But now getting the below error,

[SPLoaderError.loadComponentError]:
***Failed to load component "3a328f0a-99c4-4b28-95ab-fe0847f657a3" (ScriptEditorWebPart).
Original error: ***Failed to load URL 'https://localhost:4321/dist/script-editor-bundle.js' for resource 'script-editor-bundle' in component '3a328f0a-99c4-4b28-95ab-fe0847f657a3' (ScriptEditorWebPart). There was a network problem.
Make sure that you are running 'gulp serve' and you have run 'gulp trust-dev-cert'.

***INNERERROR:
***Failed to load URL 'https://localhost:4321/dist/script-editor-bundle.js' for resource 'script-editor-bundle' in component '3a328f0a-99c4-4b28-95ab-fe0847f657a3' (ScriptEditorWebPart). There was a network problem.
Make sure that you are running 'gulp serve' and you have run 'gulp trust-dev-cert'.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.013/sp-pages-assembly_en_95dc97007fd8cd2ab06559627831a437.js:729:15996)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.013/sp-pages-assembly_en_95dc97007fd8cd2ab06559627831a437.js:1589:21639)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.013/sp-pages-assembly_en_95dc97007fd8cd2ab06559627831a437.js:1589:15594)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.013/sp-pages-assembly_en_95dc97007fd8cd2ab06559627831a437.js:1589:11625)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.013/sp-pages-assembly_en_95dc97007fd8cd2ab06559627831a437.js:1589:69925

It is behaving weird.Sometimes working sometimes not working.

I have removed the app and added again,but no luck.

Kindly help.
