### ISSUE TITLE
Test for displaying button only when conditions are true

### ISSUE THREAD

**Issue by liricy** [SharePoint/sp-dev-fx-webparts#633]
## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

I have a render function as shown below:
```
private render(): JSX.Element {
return (
<div>
{this.props.x && this.state.y &&
   <DefaultButton 
   onClick={this.onDeleteButtonClick}
   >		
   Delete
  </DefaultButton>
}		
</div>
);
}
```

Only when the 2 conditions this.props.x and this.state.y are true, display button. 

Similarly,

```
class TitleContainer extends React.Component {
  private isPageEnabled: boolean = false;
  private isSubmitter: boolean = false;
  render() {
    return (
      <div>
        {this.isPageEnabled && this.isSubmitter &&
          <div>
            <br />
            <SubmitAppFormContainer />
          </div>
        }    
      </div>
    );
  }
}
```

Only when the 2 conditions this.isPageEnabled && this.isSubmitter are true, display SubmitAppFormContainer.
 
How do I write a test for the same? Please let me know. Thanks!

**Comment by VelinGeorgiev** [comment]
Case 1: Place an id to your component so you can find it easily 

I assume you are using Enzyme to mount the component.

```
<DefaultButton id="deleteButton"
   onClick={this.onDeleteButtonClick}
   >
```

Then you test should look like:

```
it('should delete be hidden', () => {

      reactComponent.setProps({ x: false });
      reactComponent.setState({ y: false });
 
      reactComponent.update();   

      const deleteButton = reactComponent.find("#deleteButton");
      
      expect(deleteButton.length).toBe(0);
  });

it('should delete be visible', () => {



      reactComponent.setProps({ x: true});        // https://airbnb.io/enzyme/docs/api/ReactWrapper/setProps.html

      reactComponent.setState({ y: true});  // https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/setState.md
 
      reactComponent.update();   // https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/update.md

      const deleteButton = reactComponent.find("#deleteButton");
      
      expect(deleteButton.length).toBeGreaterThan(0);
  });
```

Case 2: Turn those private variables to react state objects or react properties if they are stateless (static) then you can do the same as case 1. (Better practice is to use state instead of just private variables if the intention is to change them at some point)

Note: That is a pseudo code, but you will get the idea.

**Comment by liricy** [comment]
Thanks for your response. I updated private variables to props. This is currenly how my render component looks like:

```
 <div>
              {this.props.userRolesErrorMessage && 
                <div><span className="ms-fontColor-redDark">{this.props.userRolesErrorMessage}</span></div>
              }
              {this.props.isPageEnabled && 
                <div className="ms-font-xxl">
                  {escape(strings.Title)}
                </div>
              }  
              {this.props.isPageEnabled && this.props.isSubmitter &&
                <div>
                  <br />
                  <SubmitAppFormContainer />
                </div>
              }   
              {this.props.isPageEnabled && 
                <div>
                  <br />
                  <ListSubmissionsContainer isSubmitter={this.props.isSubmitter} isReviewer={this.props.isReviewer}/>
                </div>
              }                       
            </div>
```

I wrote a test for the part:

 {this.props.isPageEnabled && this.props.isSubmitter &&
                <div>
                  <br />
                  <SubmitAppFormContainer />
                </div>
              }   

as follows:

it("test", () => {
        const reactComponent = mount(<TitleContainer {...props} />);
        reactComponent.setProps({ isPageEnabled: true });
        reactComponent.setProps({ isSubmitter: true });
        reactComponent.update();   
        expect(reactComponent.find(SubmitAppFormContainer)).toHaveLength(1);
        reactComponent.unmount();        
    });  

It fails with error:

Invariant Violation: Could not find "store" in either the context or props of "Connect(ListSubmissionsContainer)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ListSubmissionsContainer)".

      at invariant (node_modules/invariant/invariant.js:40:15)
      at new Connect (node_modules/react-redux/lib/components/connectAdvanced.js:134:33)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:292:18
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
      at ReactCompositeComponentWrapper._constructComponentWithoutOwner (node_modules/react-dom/lib/ReactCompositeComponent.js:291:16)
      at ReactCompositeComponentWrapper._constructComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:282:19)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:185:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:43:35)
      at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:234:44)
      at ReactDOMComponent._createInitialChildren (node_modules/react-dom/lib/ReactDOMComponent.js:701:32)
      at ReactDOMComponent.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:520:12)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:43:35)
      at Object.updateChildren (node_modules/react-dom/lib/ReactChildReconciler.js:119:51)
      at ReactDOMComponent._reconcilerUpdateChildren (node_modules/react-dom/lib/ReactMultiChild.js:204:32)
      at ReactDOMComponent._updateChildren (node_modules/react-dom/lib/ReactMultiChild.js:308:31)
      at ReactDOMComponent.updateChildren (node_modules/react-dom/lib/ReactMultiChild.js:295:12)
      at ReactDOMComponent._updateDOMChildren (node_modules/react-dom/lib/ReactDOMComponent.js:944:12)
      at ReactDOMComponent.updateComponent (node_modules/react-dom/lib/ReactDOMComponent.js:758:10)
      at ReactDOMComponent.receiveComponent (node_modules/react-dom/lib/ReactDOMComponent.js:720:10)
      at Object.receiveComponent (node_modules/react-dom/lib/ReactReconciler.js:122:22)
      at ReactCompositeComponentWrapper._updateRenderedComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:751:23)
      at ReactCompositeComponentWrapper._performComponentUpdate (node_modules/react-dom/lib/ReactCompositeComponent.js:721:10)
      at ReactCompositeComponentWrapper.updateComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:642:12)
      at ReactCompositeComponentWrapper.receiveComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:544:10)
      at Object.receiveComponent (node_modules/react-dom/lib/ReactReconciler.js:122:22)
      at ReactCompositeComponentWrapper._updateRenderedComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:751:23)
      at ReactCompositeComponentWrapper._performComponentUpdate (node_modules/react-dom/lib/ReactCompositeComponent.js:721:10)
      at ReactCompositeComponentWrapper.updateComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:642:12)
      at ReactCompositeComponentWrapper.performUpdateIfNecessary (node_modules/react-dom/lib/ReactCompositeComponent.js:558:12)
      at Object.performUpdateIfNecessary (node_modules/react-dom/lib/ReactReconciler.js:154:22)
      at runBatchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:148:21)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:141:20)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/Transaction.js:141:20)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/ReactUpdates.js:87:32)
      at Object.flushBatchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:170:19)
      at ReactDefaultBatchingStrategyTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:207:25)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:154:16)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:26)
      at Object.enqueueUpdate (node_modules/react-dom/lib/ReactUpdates.js:198:22)
      at enqueueUpdate (node_modules/react-dom/lib/ReactUpdateQueue.js:22:16)
      at Object.enqueueSetState (node_modules/react-dom/lib/ReactUpdateQueue.js:216:5)
      at WrapperComponent.Object.<anonymous>.ReactComponent.setState (node_modules/react/lib/ReactBaseClasses.js:62:16)
      at WrapperComponent.setChildProps (node_modules/enzyme-adapter-utils/build/createMountWrapper.js:123:16)
      at Object.render (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:186:26)
      at ReactWrapper.setProps (node_modules/enzyme/build/ReactWrapper.js:418:24)
      at Object.<anonymous> (src/webparts/publishApps/tests/TitleContainer.test.tsx:34:24)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Please let me know what I am doing wrong.
