### ISSUE TITLE
react-list-form unable to build

### ISSUE THREAD

**Issue by Manaf-Ibrahim** [SharePoint/sp-dev-fx-webparts#739]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@semopz
@VesaJuvonen

## Expected or Desired Behavior

To be able to run gulp serve after on the cloned repo and test the functionality of the react-list-form web part.

## Observed Behavior

Stack trace as follows:

```
Build target: DEBUG
/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/node-core-library/lib/JsonSchema.js:178
            throw new Error(prefix + os.EOL +
            ^

Error: JSON validation failed:
/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/config/tslint.json

Error: #/ (Defines configuration options for the...)
       Additional properties not allowed: lintConfig,useDefaultConfigAsBase,removeExistingRules,displayAsWarning
    at validateObjectWithCallback (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/node-core-library/lib/JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/node-core-library/lib/JsonSchema.js:193:13)
    at JsonSchema.validateObject (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/node-core-library/lib/JsonSchema.js:175:14)
    at TslintCmdTask._readConfigFile (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:308:28)
    at TslintCmdTask.onRegister (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:87:32)
    at Object.initialize (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/gulp-core-build/lib/index.js:299:24)
    at SPWebBuildRig.initialize (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/sp-build-common/lib/BuildRig.js:61:19)
    at SPWebBuildRig.initialize (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/sp-build-common/lib/SPBuildRig.js:22:15)
    at SPWebBuildRig.initialize (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/sp-build-web/lib/SPWebBuildRig.js:15:15)
    at Object.exports.initialize (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/node_modules/@microsoft/sp-build-web/lib/index.js:23:17)
    at Object.<anonymous> (/Users/manafibrahim/Desktop/Coding Projects/Sharepoint/react-list-form/gulpfile.js:6:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

## Steps to Reproduce

Running npm install followed by gulp serve in working directory.

Many thanks!

**Comment by mozilla0** [comment]
For me it was working, after I've delete the file tslint.json from /config folder. Filde should existit in the root directory of the webpart.

**Comment by Manaf-Ibrahim** [comment]
Thank you very much!
