### ISSUE TITLE
React Birthdays Wont Buld

### ISSUE THREAD

**Issue by jleckard007** [SharePoint/sp-dev-fx-webparts#927]
When I go to Gulp Build on this project I get a 
internal/modules/cjs/loader.js: 638 throw error

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)

- [ ] Question
- [ X] Bug
- [] Enhancement

  @vman

**Comment by jleckard007** [comment]
I was able to resolve this issue with updating npm and gulp
