### ISSUE TITLE
Error 'tslint' when running gulp serve

### ISSUE THREAD

**Issue by clayjam** [SharePoint/sp-dev-fx-webparts#981]
## Authors
@LauraKokkarinen @wobba 

- [ ] Question
- [x] Bug
- [] Enhancement

I am getting an error after running gulp serve that I am unable to find an answer. I am running this for the react-script-editor web part on macOS.

This is error I get:

 Error - 'tslint' sub task errored after 1.79 s
 Error in plugin 'gulp-cache'
Message:
    Cannot find module 'tslint'
Details:
    code: MODULE_NOT_FOUND

**Comment by Noeky** [comment]
I have the same issue when gulp build the react-multipage webpart

**Comment by clayjam** [comment]
I have fixed this for anyone else who comes across this issue.

You need to install tslint: 
npm install tslint

**Comment by Noeky** [comment]
> I have fixed this for anyone else who comes across this issue.
> 
> You need to install tslint:
> npm install tslint

After installing npm install tslint I receive the following error 
Build target: DEBUG
C:\_dev\react-multipage\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178
            throw new Error(prefix + os.EOL +
            ^

Error: JSON validation failed:
C:\_dev\react-multipage\config\tslint.json

Error: #/ (Defines configuration options for the...)
       Additional properties not allowed: lintConfig,useDefaultConfigAsBase,removeExistingRules,displayAsWarning
    at validateObjectWithCallback (C:\_dev\react-multipage\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (C:\_dev\react-multipage\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
    at JsonSchema.validateObject (C:\_dev\react-multipage\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
    at TslintCmdTask._readConfigFile (C:\_dev\react-multipage\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:311:28)
    at TslintCmdTask.onRegister (C:\_dev\react-multipage\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
    at Object.initialize (C:\_dev\react-multipage\node_modules\@microsoft\gulp-core-build\lib\index.js:299:24)
    at SPWebBuildRig.initialize (C:\_dev\react-multipage\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
    at SPWebBuildRig.initialize (C:\_dev\react-multipage\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:28:15)
    at Object.exports.initialize (C:\_dev\react-multipage\node_modules\@microsoft\sp-build-web\lib\index.js:22:17)
    at Object.<anonymous> (C:\_dev\react-multipage\gulpfile.js:6:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
